# Setup
title:               Software Crafting Notebook
tagline:             'This is learning by teaching.'
description:         'Lessons and discoveries from my software crafting learning path.'
url:                 https://albertemozo.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alberte Mozo
  # url:               https://twitter.com/...
  email:             alberte.mozo@proton.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
